version: "3.8"

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - "3000"
    networks:
      - app-network

  webserver:
    image: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge